<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Fluxi.Api\Fluxi.Api.csproj" />
    <ProjectReference Include="..\..\src\Fluxi.Application\Fluxi.Application.csproj" />
    <ProjectReference Include="..\..\src\Fluxi.Domain\Fluxi.Domain.csproj" />
    <ProjectReference Include="..\..\src\Fluxi.Infrastructure\Fluxi.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Fluxi.SharedKernel\Fluxi.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
