<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\tests\Fluxi.Domain.Tests\Fluxi.Domain.Tests.csproj" />
    <ProjectReference Include="..\..\tests\Fluxi.SharedKernel.Tests\Fluxi.SharedKernel.Tests.csproj" />
    <ProjectReference Include="..\Fluxi.Domain\Fluxi.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="Serilog" />
  </ItemGroup>

</Project>
